AllCops:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/MixinUsage:
  Exclude:
    - 'lib/remote_ruby.rb'

Security/MarshalLoad:
  Exclude:
    - 'lib/remote_ruby/unmarshaler.rb'
